### ISSUE TITLE
Intermittent CI failure: Edit an OSHU ETD an admin user can edit all of the metadata of an Etd

### ISSUE THREAD

**Issue by bess** [curationexperts/mahonia#254] opened 2018-01-22 13:32 UTC
```

Failures:

  1) Edit an OSHU ETD an admin user can edit all of the metadata of an Etd
     Failure/Error: expect(page).to have_content "Edited Title"
       expected to find text "Edited Title" in "Skip to Content Scholar Archive Switch language English View Vance Smitham profile Vance Smitham ACTIVITY Your activity Reports REPOSITORY CONTENTS Administrative Sets Collections Works TASKS Review Submissions Sidekiq CONFIGURATION Settings Workflow Roles HomeAdministrationYour WorksMoomintrollEdit Edit Work Descriptions Files Relationships Share pdf-sample.pdf 7.95 KB Delete Add Local Files Add files... Add folder... Cancel upload Drop files here. Save Work Requirements Describe your work Add files Visibility Public Make available to all. OHSU Restrict access to OHSU. Embargo Set date for future release. Lease Set date for future reduced access. Private Keep to myself with option to share. By saving this work I agree to the Deposit Agreement Cancel"
     # ./spec/features/edit_etd_spec.rb:103:in `block (3 levels) in <top (required)>'

Finished in 7 minutes 22 seconds (files took 22.44 seconds to load)
290 examples, 1 failure, 14 pending

Failed examples:

rspec ./spec/features/edit_etd_spec.rb:23 # Edit an OSHU ETD an admin user can edit all of the metadata of an Etd

Randomized with seed 61352
```

**Comment by shanitajohn** [comment] 2018-01-24 21:34
Closing for now. Can't reproduce.

**Closed as completed by shanitajohn** 2018-01-24 21:34 UTC
Labels: wontfix, backlog
