### ISSUE TITLE
Capify the codebase

### ISSUE THREAD

**Issue by acozine** [curationexperts/mahonia#11] opened 2017-10-05 19:24 UTC
Acceptance:

- [ ] add capistrano
- [ ] by default, deploys master
- [ ] can deploy branches
- [ ] includes basic shared files (blacklight.yml, browse_everything_providers.yml, database.yml, fedora.yml, redis.yml, solr.yml, config/environments/production.rb, config/initializers/hyrax.rb)

**Comment by no-reply** [comment] 2017-10-12 17:51
Is this a duplicate of #40?

**Comment by mark-dce** [comment] 2017-10-17 01:44
Yes, It seems like this is covered in #40 and #36

**Closed as completed** 2017-10-17 01:46 UTC
